# travis.yml

os:
  - linux

language: c

compiler:
  - gcc
  - clang

matrix:
  exclude:
      - os: osx
        compiler: gcc

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    packages:
      - gcc-4.8
      - g++-4.8

script:
  - build_test.sh
  - prince-c-ref

