# travis.yml

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

matrix:
  exclude:
      - os: osx
        compiler: gcc

sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5.1" CC="gcc-5.1"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.1
    - g++-5.1
    - clang

script:
  - ./build_test.sh
  - ls
  - g++ --version
  - $CXX --version
  - $CC --version
  - ./prince-c-ref

